version: "3.9"

services:
  pubsub:
    image: breyr/dpanel-pubsub-go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway" # needed for linux
  fastapi:
    image: breyr/dpanel-fastapi
    ports:
      - 5002:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - composefiles:/app/composefiles # where compose files are stored on fastapi container
    restart: on-failure
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway" # needed for linux
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway" # needed for linux

# name volume to hold uploaded compose files
volumes:
  composefiles:
