version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx:/app # bind mount for development
    ports:
      - 3000:3000
  web:
    build:
      context: ./web
    image: dpanel:latest
    ports:
      - 5001:5001
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./web:/app # bind mount for development
    depends_on:
      - redis
  pubsub:
    build:
      context: ./pubsub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
