version: "3.9"

services:
  pubsub:
    build:
      context: ./pubsub-go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fastapi:
    build:
      context: ./fastapi
    ports:
      - 5002:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./composefiles:/code/composefiles # where compose files are stored on host machine
    restart: on-failure
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
