version: "3.9"

services:
  web:
    image: dpanel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app # necessary for development
