version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./nginx
          target: /app
  pubsub:
    build:
      context: ./pubsub-go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./pubsub-go/main.go
          target: /app
  fastapi:
    build:
      context: ./fastapi
    ports:
      - 5002:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./composefiles:/code/composefiles # where compose files are stored on host machine
    restart: on-failure
    depends_on:
      - redis
    develop:
      watch:
        - action: sync+restart
          path: ./fastapi
          target: /code
  redis:
    image: redis:latest
    ports:
      - 6379:6379
