version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    image: dpanel:latest
    ports:
      - 5001:5000
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app # necessary for development
    depends_on:
      - redis
  pubsub:
    build:
      context: .
      dockerfile: Dockerfile.pubsub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
